{{- if and .Values.persistence.worker.enabled (not .Values.persistence.worker.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: {{ template "erpnext.name" . }}
    chart: {{ template "erpnext.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "erpnext.fullname" . }}
spec:
  accessModes:
  {{- range .Values.persistence.worker.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.worker.size | quote }}
  storageClassName: {{ required "A valid persistence.worker.storageClass entry required!" .Values.persistence.worker.storageClass }}
{{- end }}
